[package]
name = "riichi-in-rust"
version = "0.0.42"
authors = ["harphield <harphield@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = { version = "0.7", features = ["wasm-bindgen"] }
console_error_panic_hook = "0.1.6"
